version: '3'

services:
###> doctrine/doctrine-bundle ###
  # database:
  #   image: postgres:${POSTGRES_VERSION:-15}-alpine
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #     # You should definitely change the password in production
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
  #     POSTGRES_USER: ${POSTGRES_USER:-app}
  #   volumes:
  #     - database_data:/var/lib/postgresql/data:rw

  # database:
  #   image: mysql:8.0
  #   ports:
  #     - "3308:3308"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: guestbook
  #   volumes:
  #     - ./var:/var/www/var
  #     - ./tools/docker/mysql:/var/lib/mysql

  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     APP_ENV: dev
  #     ADMINER_DEFAULT_SERVER: database
  #     ADMINER_DESIGN: pepa-linha



      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
